repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.11
    hooks:
      - id: ruff-check     # Linter: verifica errores y malas prácticas
      - id: ruff-format    # Formatter: da formato automático
